kind: Job
apiVersion: batch/v1
metadata: 
  name: demo-job
  namespace: nginx
spec: 
  completions: 1
  parallelism: 1
  template: 
    metadata: 
      name: demo-job-pod
      labels: 
        app: batch-task
    spec: 
      containers:
        - name: batch-container
          image: busybox:latest
          commnad: ["sh", "-c", "echo Hello friends! && sleep 10"]
      restartPolicy: Never
 